/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto


/**
 * 
 * @param Id 
 * @param WorkCenterId 
 * @param PrevOperationId 
 * @param OperationId 
 * @param Duration 
 */
data class AdjustmentDTO (
    val Id: kotlin.Long? = null,
    val WorkCenterId: kotlin.Long? = null,
    val PrevOperationId: kotlin.Long? = null,
    val OperationId: kotlin.Long? = null,
    val Duration: kotlin.String? = null
)

