/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param WorkCenterId 
 * @param OperationId 
 * @param PrevOperationId 
 * @param Duration 
 */
data class AdjustmentIM (
    val WorkCenterId: kotlin.Long? = null,
    val OperationId: kotlin.Long? = null,
    val PrevOperationId: kotlin.Long? = null,
    val Duration: kotlin.String? = null
)

