/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto


/**
 * 
 * @param product 
 * @param order 
 * @param batch 
 * @param quantity 
 * @param process 
 * @param orderStartDate 
 * @param orderFinishDate 
 * @param finishDate 
 */
data class BatchForecastDatesDTO (
    val product: kotlin.String? = null,
    val order: kotlin.String? = null,
    val batch: kotlin.Int? = null,
    val quantity: kotlin.Int? = null,
    val process: kotlin.String? = null,
    val orderStartDate: java.time.LocalDateTime? = null,
    val orderFinishDate: java.time.LocalDateTime? = null,
    val finishDate: java.time.LocalDateTime? = null
)

