/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param product 
 * @param order 
 * @param batch 
 * @param quantity 
 * @param workCenter 
 * @param process 
 * @param operationOrder 
 * @param operationMode 
 * @param startDate 
 * @param finishDate 
 */
data class DailyReportItemDTO (
    val product: kotlin.String? = null,
    val order: kotlin.String? = null,
    val batch: kotlin.Int? = null,
    val quantity: kotlin.Int? = null,
    val workCenter: kotlin.String? = null,
    val process: kotlin.String? = null,
    val operationOrder: kotlin.Int? = null,
    val operationMode: kotlin.String? = null,
    val startDate: java.time.LocalDateTime? = null,
    val finishDate: java.time.LocalDateTime? = null
)

