/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto


/**
 * 
 * @param contentType 
 * @param contentDisposition 
 * @param headers 
 * @param length 
 * @param name 
 * @param fileName 
 */
data class IFormFile (
    val contentType: kotlin.String? = null,
    val contentDisposition: kotlin.String? = null,
    val headers: kotlin.collections.Map<kotlin.String, kotlin.Array<kotlin.String>>? = null,
    val length: kotlin.Long? = null,
    val name: kotlin.String? = null,
    val fileName: kotlin.String? = null
)

