/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto


/**
 * 
 * @param Id 
 * @param Name 
 * @param PrepareOperationDuration 
 * @param OperationDuration 
 * @param CompletionOperationDuration 
 * @param CompletionWorkCentrDuration 
 * @param Multiplicity 
 * @param WorkCenters 
 */
data class OperationModeDTO (
    val Id: kotlin.Long? = null,
    val Name: kotlin.String? = null,
    val PrepareOperationDuration: kotlin.String? = null,
    val OperationDuration: kotlin.String? = null,
    val CompletionOperationDuration: kotlin.String? = null,
    val CompletionWorkCentrDuration: kotlin.String? = null,
    val Multiplicity: kotlin.Int? = null,
    val WorkCenters: kotlin.Array<kotlin.Long>? = null
)

