/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param Name 
 * @param Params 
 */
data class OptimizationCriteriaIM (
    val Name: kotlin.String? = null,
    val Params: kotlin.Array<kotlin.Any>? = null
)

