/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto

/**
 * 
 * @param Operation 
 * @param WorkCenter 
 * @param Batch 
 * @param StartDate 
 * @param StartExecutionDate 
 * @param FinishDate 
 * @param WorkCenterFinishDate 
 */
data class ProblemScheduleItemDTO (
    val Operation: ScheduleItemOperationDTO? = null,
    val WorkCenter: ScheduleItemWorkCenterDTO? = null,
    val Batch: ScheduleItemBatchDTO? = null,
    val StartDate: java.time.LocalDateTime? = null,
    val StartExecutionDate: java.time.LocalDateTime? = null,
    val FinishDate: java.time.LocalDateTime? = null,
    val WorkCenterFinishDate: java.time.LocalDateTime? = null
)

