/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


//import com.squareup.moshi.Json
///**
// *
// * @param CurrentOptimum
// * @param Id
// * @param Status
// * @param Timestamp
// */
//data class ProblemWithSolutionFitnessDTO (
//    val CurrentOptimum: kotlin.Double? = null,
//    val Id: kotlin.Long? = null,
//    val Status: ProblemWithSolutionFitnessDTO.Status? = null,
//    val Timestamp: kotlin.Long? = null
//) {
//
//    /**
//    *
//    * Values: created,processing,solutionFound,irrelevant,resolved,error
//    */
//    enum class Status(val value: kotlin.String){
//
//        @Json(name = "Created") created("Created"),
//
//        @Json(name = "Processing") processing("Processing"),
//
//        @Json(name = "SolutionFound") solutionFound("SolutionFound"),
//
//        @Json(name = "Irrelevant") irrelevant("Irrelevant"),
//
//        @Json(name = "Resolved") resolved("Resolved"),
//
//        @Json(name = "Error") error("Error");
//
//    }
//
//}
//
