/**
 * MES
 * MES API Reference
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.triplepi.projectilemes.data.network.dto

import com.google.gson.annotations.SerializedName

/**
 *
 * @param Id
 * @param Status
 * @param Timestamp
 */
data class ProblemDTO(
    @SerializedName("Id") val id: Long? = null,
    @SerializedName("Status") val status: ProblemDTO.Status? = null,
    @SerializedName("Timestamp") val timestamp: Long? = null
) {

    /**
     * Values: created,processing,solutionFound,irrelevant,resolved,error
     */
    enum class Status(val value: String) {
        @SerializedName("Created")
        created("Created"),
        @SerializedName("Processing")
        processing("Processing"),
        @SerializedName("SolutionFound")
        solutionFound("SolutionFound"),
        @SerializedName("Irrelevant")
        irrelevant("Irrelevant"),
        @SerializedName("Resolved")
        resolved("Resolved"),
        @SerializedName("Error")
        error("Error");
    }
}

