/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.TechnologicalProcessIM

/**
 * 
 * @param Id 
 * @param Name 
 * @param Processes 
 */
data class ProductIM (
    val Id: kotlin.Long? = null,
    val Name: kotlin.String? = null,
    val Processes: kotlin.Array<TechnologicalProcessIM>? = null
)

