/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto

/**
 * 
 * @param FixItems 
 */
data class RePlanningSettingsIM (
    val FixItems: kotlin.Array<FixScheduleItemIM>
)

