/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.ScheduleItemProgressIM

//import com.squareup.moshi.Json
///**
// *
// * @param Date
// * @param Action
// * @param Progress
// * @param WorkCenterFinishDate
// */
//data class ScheduleItemActionIM (
//    val Date: java.time.LocalDateTime,
//    val Action: ScheduleItemActionIM.Action,
//    val Progress: ScheduleItemProgressIM? = null,
//    val WorkCenterFinishDate: java.time.LocalDateTime? = null
//) {
//
//    /**
//    *
//    * Values: start,startExecution,finish,`suspend`,resume,executePartial,progress
//    */
//    enum class Action(val value: kotlin.String){
//
//        @Json(name = "Start") start("Start"),
//
//        @Json(name = "StartExecution") startExecution("StartExecution"),
//
//        @Json(name = "Finish") finish("Finish"),
//
//        @Json(name = "Suspend") `suspend`("Suspend"),
//
//        @Json(name = "Resume") resume("Resume"),
//
//        @Json(name = "ExecutePartial") executePartial("ExecutePartial"),
//
//        @Json(name = "Progress") progress("Progress");
//
//    }
//
//}
//
