/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.ScheduleItemIM

/**
 * 
 * @param Items 
 * @param Begin 
 */
data class ScheduleIM (
    val Items: kotlin.Array<ScheduleItemIM>,
    val Begin: java.time.LocalDateTime
)

