/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto


/**
 * 
 * @param Id 
 * @param Number 
 * @param Quantity 
 * @param FactQuantity 
 * @param OrderId 
 * @param OrderNumber 
 * @param StartOperationId 
 */
data class ScheduleItemBatchDTO (
    val Id: kotlin.Long? = null,
    val Number: kotlin.Int? = null,
    var Quantity: kotlin.Int? = null,
    val FactQuantity: kotlin.Int? = null,
    val OrderId: kotlin.Long? = null,
    val OrderNumber: kotlin.String? = null,
    val StartOperationId: kotlin.Long? = null
)

