/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto


/**
 * 
 * @param product 
 * @param order 
 * @param batch 
 * @param quantity 
 * @param process 
 * @param operationOrder 
 * @param operationName 
 * @param workCenter 
 * @param startDate 
 * @param finishDate 
 * @param duration 
 * @param durationPerUnit 
 * @param prevBatchOperationFinishDate 
 * @param prevWorkCenterOperationFinishDate 
 * @param workCenterDelay 
 */
data class ScheduleItemDetailedDTO (
    val product: kotlin.String? = null,
    val order: kotlin.String? = null,
    val batch: kotlin.Int? = null,
    val quantity: kotlin.Int? = null,
    val process: kotlin.String? = null,
    val operationOrder: kotlin.Int? = null,
    val operationName: kotlin.String? = null,
    val workCenter: kotlin.String? = null,
    val startDate: java.time.LocalDateTime? = null,
    val finishDate: java.time.LocalDateTime? = null,
    val duration: kotlin.String? = null,
    val durationPerUnit: kotlin.Double? = null,
    val prevBatchOperationFinishDate: java.time.LocalDateTime? = null,
    val prevWorkCenterOperationFinishDate: java.time.LocalDateTime? = null,
    val workCenterDelay: kotlin.String? = null
)

