/**
 * MES
 * MES API Reference
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.triplepi.projectilemes.data.network.dto

import com.google.gson.annotations.SerializedName

/**
 *
 * @param Date
 * @param Action
 * @param Progress
 * @param WorkCenterFinishDate
 */
data class ScheduleItemActionIM(
    val Date: java.time.LocalDateTime,
    @SerializedName("Action") val action: Action,
    val Progress: ScheduleItemProgressIM? = null,
    val WorkCenterFinishDate: java.time.LocalDateTime? = null
) {

    /**
     *
     * Values: start,startExecution,finish,`suspend`,resume,executePartial,progress
     */
    enum class Action(val value: kotlin.String) {

        @SerializedName("Start")
        start("Start"),

        @SerializedName("StartExecution")
        startExecution("StartExecution"),

        @SerializedName("Finish")
        finish("Finish"),

        @SerializedName("Suspend")
        `suspend`("Suspend"),

        @SerializedName("Resume")
        resume("Resume"),

        @SerializedName("ExecutePartial")
        executePartial("ExecutePartial"),

        @SerializedName("Progress")
        progress("Progress");

    }

}

