/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto


/**
 * 
 * @param Id 
 * @param Count 
 * @param BaseOnId 
 * @param SolutionId 
 */
data class ScheduleItemLeftoverDTO (
    val Id: kotlin.Long? = null,
    val Count: kotlin.Int? = null,
    val BaseOnId: kotlin.Long? = null,
    val SolutionId: kotlin.Long? = null
)

