/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param Count 
 * @param Comment 
 */
data class ScheduleItemProgressQuarantineIM (
    val Comment: kotlin.String,
    val Count: kotlin.Int? = null
)

