/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto


/**
 * 
 * @param Name 
 * @param ProductName 
 * @param ProductId 
 * @param ModeId 
 * @param OperationId 
 * @param TechnologyProcessId 
 */
data class ScheduleItemOperationDTO (
    val Name: kotlin.String? = null,
    val ProductName: kotlin.String? = null,
    val ProductId: kotlin.Long? = null,
    val ModeId: kotlin.Long? = null,
    val OperationId: kotlin.Long? = null,
    val TechnologyProcessId: kotlin.Long? = null
)

