/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


//import com.squareup.moshi.Json
///**
// *
// * @param Date
// * @param Action
// */
//data class ScheduleItemManageActionIM (
//    val Date: java.time.LocalDateTime,
//    val Action: ScheduleItemManageActionIM.Action
//) {
//
//    /**
//    *
//    * Values: undo,reset
//    */
//    enum class Action(val value: kotlin.String){
//
//        @Json(name = "Undo") undo("Undo"),
//
//        @Json(name = "Reset") reset("Reset");
//
//    }
//
//}
//
