/**
 * MES
 * MES API Reference
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.triplepi.projectilemes.data.network.dto

import com.google.gson.annotations.SerializedName


/**
 *
 * @param Id
 * @param Operation
 * @param WorkCenter
 * @param Batch
 * @param StartDate
 * @param StartExecutionDate
 * @param FinishDate
 * @param WorkCenterFinishDate
 * @param Timestamp
 * @param FactStartDate
 * @param FactFinishDate
 * @param FactWorkCenterFinishDate
 * @param FactStartExecutionDate
 * @param PlanCount
 * @param FactCount
 * @param QuarantineCount
 * @param Leftover
 * @param LeftoverSolution
 * @param Status
 */
data class ScheduleItemDTO(
    val Id: Long? = null,
    val Operation: ScheduleItemOperationDTO? = null,
    val WorkCenter: ScheduleItemWorkCenterDTO? = null,
    val Batch: ScheduleItemBatchDTO? = null,
    val StartDate: String? = null,
    val StartExecutionDate: String? = null,
    val FinishDate: String? = null,
    val WorkCenterFinishDate: String? = null,
    val Timestamp: Long? = null,
    val FactStartDate: String? = null,
    val FactFinishDate: String? = null,
    val FactWorkCenterFinishDate: String? = null,
    val FactStartExecutionDate: String? = null,
    val PlanCount: Int? = null,
    val FactCount: Int? = null,
    val QuarantineCount: Int? = null,
    val Leftover: ScheduleItemLeftoverDTO? = null,
    val LeftoverSolution: ScheduleItemLeftoverDTO? = null,
    @SerializedName("Status") val status: Status? = null
) {

    /**
     *
     * Values: New,started,executionStarted,finished,suspending
     */

    enum class Status(val value: String) {

        @SerializedName("New")
        New("New"),

        @SerializedName("Started")
        Started("Started"),

        @SerializedName("ExecutionStarted")
        ExecutionStarted("ExecutionStarted"),

        @SerializedName("Finished")
        Finished("Finished"),

        @SerializedName("Suspending")
        Suspending("Suspending");

    }

}

