/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param StartDate 
 * @param StartExecutionDate 
 * @param FinishDate 
 * @param WorkCenterFinishDate 
 * @param BatchId 
 * @param OperationId 
 * @param OperationModeId 
 * @param WorkCenterId 
 */
data class ScheduleItemIM (
    val StartDate: java.time.LocalDateTime,
    val StartExecutionDate: java.time.LocalDateTime,
    val FinishDate: java.time.LocalDateTime,
    val WorkCenterFinishDate: java.time.LocalDateTime,
    val BatchId: kotlin.Long? = null,
    val OperationId: kotlin.Long? = null,
    val OperationModeId: kotlin.Long? = null,
    val WorkCenterId: kotlin.Long? = null
)

