/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto

import com.triplepi.projectilemes.data.network.dto.ScheduleItemProgressProcessedIM
import com.triplepi.projectilemes.data.network.dto.ScheduleItemProgressQuarantineIM

/**
 * 
 * @param Processed 
 * @param Quarantine 
 */
data class ScheduleItemProgressIM (
    val Processed: ScheduleItemProgressProcessedIM? = null,
    val Quarantine: ScheduleItemProgressQuarantineIM? = null
)

