/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param Id 
 * @param Timestamp 
 */
data class ScheduleItemDeletedDTO (
    val Id: kotlin.Long? = null,
    val Timestamp: kotlin.Long? = null
)

