/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto

/**
 * 
 * @param Id 
 * @param Number 
 * @param StartDate 
 * @param DeadlineDate 
 * @param Priority 
 * @param Batches 
 */
data class TimelineOrderDTO (
    val Id: kotlin.Long? = null,
    val Number: kotlin.String? = null,
    val StartDate: java.time.LocalDateTime? = null,
    val DeadlineDate: java.time.LocalDateTime? = null,
    val Priority: kotlin.Int? = null,
    val Batches: kotlin.Array<TimelineOrderBatchDTO>? = null
)

