/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto

import com.triplepi.projectilemes.data.network.dto.TimelineProcessOperationDTO

/**
 * 
 * @param Id 
 * @param ProductName 
 * @param Operations 
 */
data class TimelineProcessDTO (
    val Id: kotlin.Long? = null,
    val ProductName: kotlin.String? = null,
    val Operations: kotlin.Array<TimelineProcessOperationDTO>? = null
)

