/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.TimelineProcessOperationModeDTO

/**
 * 
 * @param Id 
 * @param OperationModes 
 */
data class TimelineProcessOperationDTO (
    val Id: kotlin.Long? = null,
    val OperationModes: kotlin.Array<TimelineProcessOperationModeDTO>? = null
)

