/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param StartDate 
 * @param FinishDate 
 * @param WorkCenterId 
 */
data class TimelineWorkCenterServiceDTO (
    val StartDate: java.time.LocalDateTime? = null,
    val FinishDate: java.time.LocalDateTime? = null,
    val WorkCenterId: kotlin.Long? = null
)

