/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto


/**
 * 
 * @param OperationId 
 * @param WorkCenterId 
 * @param WorkCenterFinishDate 
 */
data class TimelineWorkCenterLastOperationDTO (
    val OperationId: kotlin.Long? = null,
    val WorkCenterId: kotlin.Long? = null,
    val WorkCenterFinishDate: java.time.LocalDateTime? = null
)

