/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param Id 
 * @param Name 
 * @param WorkCenters 
 */
data class TimelineProcessOperationModeDTO (
    val Id: kotlin.Long? = null,
    val Name: kotlin.String? = null,
    val WorkCenters: kotlin.Array<kotlin.Long>? = null
)

