/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.triplepi.projectilemes.data.network.dto


/**
 * 
 * @param ProcessId 
 * @param Quantity 
 * @param OperationModeId 
 * @param OperationDuration 
 * @param WorkCenterDuration 
 */
data class TimelineDurationForBatchDTO (
    val ProcessId: kotlin.Long? = null,
    val Quantity: kotlin.Int? = null,
    val OperationModeId: kotlin.Long? = null,
    val OperationDuration: kotlin.Int? = null,
    val WorkCenterDuration: kotlin.Int? = null
)

