/**
* MES
* MES API Reference
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.DateTimeRangeIM

/**
 * 
 * @param Start 
 * @param Finish 
 * @param WorkingTimes 
 */
data class WorkCenterWorkingTimeIM (
    val Start: java.time.LocalDateTime? = null,
    val Finish: java.time.LocalDateTime? = null,
    val WorkingTimes: kotlin.Array<DateTimeRangeIM>? = null
)

